### PR TITLE
Updates for Tabular-fits reader/writer fix

### PR DESCRIPTION
**Pull request by dhomeier**
Added commits to support `store_data_header` in writer and test roundtrip for both options.

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
Looks reasonable to me, thanks. I still kind of want to just store both all the time, but this is a good compromise.

**Comment by dhomeier** [comment]
If there is a use case for really having copies written to both HDUs, we could certainly restore that – I thought it was just added as a hack while the behaviour of the reader was kind of unspecified. Or the option could be changed to accept either one HDU or both together.

**Comment by rosteen** [comment]
I meant store both the primary header and data header, not copy one to multiple HDUs. Can be a potential future improvement/change.

**Comment by dhomeier** [comment]
Oh you mean on the _reader_ side? I did not touch that here, but of course extending the options would apply there as well, only one would then have to come up with a scheme for storing two or more headers in one `meta`, and that has been also discussed a couple of times without clear result.

**Comment by rosteen** [comment]
"Discussed extensively without clear result" is exactly why I decided not to go down that rabbit hole right now 😅

**Pull request merged**
